
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Property Page -> Sensor Controller
 *****************************************************************************/

 enum hyspex_eQuery 
{
  eQUERY_UNSPECIFIED = 0;
  eQUERY_STATE = 1;
  eQUERY_LENSES = 2;
}

message hyspex_QueryState_1 
{
	hyspex_eQuery query = 1;
}


/******************************************************************************
 * Sensor Controller -> Property Page
 *****************************************************************************/

 message hyspex_CurrentState_1 
{
	bool valid = 1;
	uint32 average_frame = 2;
    uint32 frame_period_us = 3;
    uint32 min_frame_period_us = 4;
    uint32 integration_time_us = 5;
    uint32 max_integration_time_us = 6;
    string lens_name = 7;
    uint32 num_backgrounds = 8;
}

