
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Property Page -> Sensor Controller
 *****************************************************************************/

message hyspex_SetAverageFrames_1 
{
    uint32 average_frame = 1;
}

message hyspex_SetFramePeriod_1 
{
    uint32 frame_period_us = 1;
}

message hyspex_SetIntegrationTime_1 
{
    uint32 integration_time_us = 1;
}

message hyspex_SetLens_1 
{
    string lens_name = 1;
}

message hyspex_SetNumOfBackgrounds_1 
{
    uint32 num_backgrounds = 1;
}


/******************************************************************************
 * Sensor Controller -> Property Page
 *****************************************************************************/

 message hyspex_CurrentState_1 
{
	bool valid = 1;
	uint32 average_frame = 2;
    uint32 frame_period_us = 3;
    uint32 min_frame_period_us = 4;
    uint32 integration_time_us = 5;
    uint32 max_integration_time_us = 6;
    string lens_name = 7;
    uint32 num_backgrounds = 8;
}

 message hyspex_LensNames_1 
{
    string lens_name_0 = 1;
    string lens_name_1 = 2;
    string lens_name_2 = 3;
    string lens_name_3 = 4;
    string lens_name_4 = 5;
    string lens_name_5 = 6;
    string lens_name_6 = 7;
    string lens_name_7 = 8;
    string lens_name_8 = 9;
    string lens_name_9 = 10;
}

