
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Property Page <-> Sensor Controller
 *****************************************************************************/

 enum ouster_eQuery 
{
  eQUERY_UNSPECIFIED = 0;
  eQUERY_STATE = 1;
  eQUERY_LIDAR_MODE = 2;
  eQUERY_AZIMUTH_WINDOW = 3;
}

message ouster_QueryMessage_1 
{
	ouster_eQuery query = 1;
}

message ouster_AzimuthWindowMessage_1
{
    double min_deg = 1;
    double max_deg = 2;
}

message ouster_LidarModeMessage_1 
{
	string mode = 1;
}

 message ouster_StateMessage_1 
{
	bool valid = 1;
	string mode = 2;
    double azimuth_min_deg = 3;
    double azimuth_max_deg = 4;
}

