
// We are using Protobuf syntax version three.

syntax = "proto3";

// A Timestamp represents a point in time independent of any time zone or local
// calendar, encoded as a count of seconds and fractions of seconds at
// nanosecond resolution. The count is relative to an epoch at UTC midnight on
// January 1, 1970, in the proleptic Gregorian calendar which extends the
// Gregorian calendar backwards to year one.
//
//import "google/protobuf/timestamp.proto";


/******************************************************************************
 * Property Page -> Sensor Controller
 *****************************************************************************/

message QueryState_1 
{
}

message SetActiveCameraId_1
{
    uint32 camera_id = 1;
}

message SetLidarMode_1 
{
	string mode = 1;
}


/******************************************************************************
 * Sensor Controller -> Property Page
 *****************************************************************************/

 message CurrentState_1 
{
	bool valid = 1;
	uint32 camera_id = 2;
    string resolution = 3;
    uint32 frames_per_second = 4;
}

