
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Property Page <-> Sensor Controller
 *****************************************************************************/

enum lucid_eQuery 
{
  eQUERY_UNSPECIFIED = 0;
  eQUERY_STATE = 1;
  eQUERY_ACTIVE_CAMERA_ID = 2;
  eQUERY_IMAGE_SIZE = 3;
  eQUERY_FRAME_RATE = 4;
}

message lucid_QueryMessage_1 
{
	lucid_eQuery query = 1;
}

message lucid_ActiveCameraIdMessage_1
{
    uint32 camera_id = 1;
}

message lucid_ImageSizeMessage_1 
{
	uint32 width = 1;
	uint32 height = 2;
}

message lucid_FrameRateMessage_1 
{
	uint32 frames_per_second = 1;
}

message lucid_StateMessage_1 
{
	bool   valid = 1;
	uint32 camera_id = 2;
	uint32 width = 3;
	uint32 height = 4;
    uint32 frames_per_second = 5;
}

message lucid_StateMessage_2
{
	bool   valid = 1;
	uint32 active_camera_id = 2;
	uint32 width = 3;
	uint32 height = 4;
    uint32 frames_per_second = 5;
	uint32 min_camera_id = 6;
	uint32 max_camera_id = 7;
}

