
// We are using Protobuf syntax version three.

syntax = "proto3";

// A Timestamp represents a point in time independent of any time zone or local
// calendar, encoded as a count of seconds and fractions of seconds at
// nanosecond resolution. The count is relative to an epoch at UTC midnight on
// January 1, 1970, in the proleptic Gregorian calendar which extends the
// Gregorian calendar backwards to year one.
//
//import "google/protobuf/timestamp.proto";


/******************************************************************************
 * General Control Packets   Ceres -> Remote Client
 *****************************************************************************/

message OpenDataFile_1 
{
	string filename = 1;
}

message ExperimentState_1 
{
	bool state = 1;
}

message ExperimentInfo_1 
{
	string title = 1;
	string researcher = 2;
	string cultivar = 3;
	string file = 4;
}

message ExperimentInfo_2 
{
	string title = 1;
	string researcher = 2;
	string cultivar = 3;
	string file = 4;
	string species = 5;
}

message PrincipalInvestigator_1
{
	string pi = 1;
}

message Researcher_1
{
	string researcher = 1;
}

message ConstructName_1
{
	string construct_name = 1;
}

message EventNumber_1
{
	string event_number = 1;
}

message FieldDesign_1
{
	string field_design = 1;
}

message PlantingDate_1
{
	uint64 planting_date = 1;
}

message HarvestDate_1
{
	uint64 harvest_date = 1;
}

message ExperimentTreatment_1
{
	string treatment = 1;
}

message ExperimentComment_1
{
	string comment = 1;
}

message ExperimentPermitInfo_1
{
	string permit = 1;
}


/******************************************************************************
 * General Reply Packets   Remote Client -> Ceres
 *****************************************************************************/

 message FileOpenState_1 
{
	bool isopen = 1;
}


/******************************************************************************
 * General Packets   Remote Client -> Ceres
 *****************************************************************************/

message StatusMessage_1 
{
	string message = 1;
}

message LogMessage_1 
{
	uint32 msg_type = 1;
	string device = 2;
	string message = 3;
}

message SensorStatus_1 
{
	string device = 1;
	string message = 2;
}

message SensorNameChange_1 
{
	string old_name = 1;
	string new_name = 2;
}

message SensorPropertyConnectInfo_1 
{
	string device = 1;
	string model = 2;
	uint32 version = 3;
	string name = 4;
	string ip_address = 5;
	uint32 port = 6;
}
