
// We are using Protobuf syntax version three.

syntax = "proto3";

// A Timestamp represents a point in time independent of any time zone or local
// calendar, encoded as a count of seconds and fractions of seconds at
// nanosecond resolution. The count is relative to an epoch at UTC midnight on
// January 1, 1970, in the proleptic Gregorian calendar which extends the
// Gregorian calendar backwards to year one.
//
//import "google/protobuf/timestamp.proto";

/******************************************************************************
 * Spidercam Packets
 *****************************************************************************/

message Spidercam_Position_1 
{
	bool   dataValid = 1;
	uint32 x_mm = 2;
	uint32 y_mm = 3;
	uint32 z_mm = 4;
	uint32 speed_mmps = 5;
	float  pan_deg = 6;
	float  pitch_deg = 7;
	float  roll_deg = 8;
	uint64 timestamp = 9;
}

