
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Enums used in various messages
 *****************************************************************************/

enum teledyne_eQuery 
{
  eQUERY_UNSPECIFIED = 0;
  eQUERY_STATE = 1;
  eQUERY_MODE = 2;
  eQUERY_IMAGE_SIZE = 3;
  eQUERY_FRAME_RATE = 4;
  eQUERY_LAPSE_INTERVAL = 5;
  eQUERY_THERMAL_RANGE = 6;
}

 enum teledyne_eReply
{
    eReply_GOOD = 0;
    eReply_FAILED = 1;
    eReply_ABORTED = 2;
    eReply_PENDING = 3;
}


/******************************************************************************
 * Property Page <-> Sensor Controller
 *****************************************************************************/

message teledyne_QueryMessage_1 
{
	teledyne_eQuery query = 1;
}

message teledyne_CameraModeMessage_1
{
    uint32 mode = 1;
}

message teledyne_ImageSizeMessage_1 
{
	uint32 width = 1;
	uint32 height = 2;
}

message teledyne_FrameRateMessage_1 
{
	double frames_per_second = 1;
}

message teledyne_LapseIntervalMessage_1 
{
	uint32 lapse_interval_ms = 1;
}

message teledyne_ThermalRangeMessage_1 
{
	float min_thermal_value_K = 1;
	float max_thermal_value_K = 2;
}


/******************************************************************************
 * Property Page -> Sensor Controller
 *****************************************************************************/

message teledyne_TakePhoto_1 
{
	bool update_view = 1;
}

message teledyne_TakePhoto_2 
{
	bool update_view = 1;
	bool auto_save   = 2;
}


/******************************************************************************
 * Sensor Controller -> Property Page
 *****************************************************************************/

message teledyne_StateMessage_1 
{
	bool   valid = 1;
	uint32 mode = 2;
	uint32 width = 3;
	uint32 height = 4;
    double frames_per_second = 5;
    uint32 lapse_interval_ms = 6;
    optional double min_frames_per_second = 7;
    optional double max_frames_per_second = 8;
    optional float min_thermal_value_K = 9;
    optional float max_thermal_value_K = 10;
}

message teledyne_Reply_1 
{
	teledyne_eReply reply = 1;
}



