
// We are using Protobuf syntax version three.

syntax = "proto3";

// Google protobuf does not support namespaces.  To avoid linker name conficts 
// all messages must start with "namespace" name


/******************************************************************************
 * Enums used in various messages
 *****************************************************************************/

 enum gps_eQuery 
{
    eQUERY_UNSPECIFIED = 0;
    eQUERY_REFERENCE_DATA = 1;
    eQUERY_REFERENCE_PARAMETERS = 2;
    eQUERY_REFERENCE_STATE = 3;
}

enum gps_eReferenceCommand
{
    eReferenceCmd_START = 0;
    eReferenceCmd_ABORT = 1;
}

enum gps_eReferenceReply
{
    eReferenceReply_GOOD = 0;
    eReferenceReply_FAILED = 1;
    eReferenceReply_ABORTED = 2;
    eReferenceReply_PENDING = 3;
    eReferenceReply_IDLE = 4;
}


/******************************************************************************
 * Property Page -> Sensor Controller
 *****************************************************************************/

message gps_QueryMessage_1 
{
	gps_eQuery query = 1;
}

message gps_SetReferenceParameters_1 
{
    uint32 min_integration_time_sec = 1;
    uint32 max_integration_time_sec = 2;
    uint32 ref_error_threshold_mm = 3;
}

message gps_ReferenceCommand_1 
{
    gps_eReferenceCommand command = 1;
}


/******************************************************************************
 * Sensor Controller -> Property Page
 *****************************************************************************/

message gps_ReferenceParameters_1 
{
	bool valid = 1;
    uint32 integration_time_sec = 2;
    uint32 max_integration_time_sec = 3;
}

message gps_ReferenceData_1 
{
	bool   valid = 1;
    double avg_lat_rad = 2;
    double avg_lng_rad = 3;
    double avg_height_m = 4;
    double std_lat_rad = 5;
    double std_lng_rad = 6;
    double std_height_m = 7;
	bool   height_valid = 8;
}

message gps_RefCommandReply_1 
{
	gps_eReferenceReply reply = 1;
}

